[2023-05-07T01:19:56.442+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-07T00:00:00+00:00 [queued]>
[2023-05-07T01:19:56.474+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-07T00:00:00+00:00 [queued]>
[2023-05-07T01:19:56.497+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-07T01:19:56.532+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-07T01:19:56.552+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-07T01:19:56.592+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_1-8> on 2023-05-07 00:00:00+00:00
[2023-05-07T01:19:56.601+0000] {standard_task_runner.py:55} INFO - Started process 517 to run task
[2023-05-07T01:19:56.612+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_1-8', 'scheduled__2023-05-07T00:00:00+00:00', '--job-id', '2636', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmpz3hxa90u']
[2023-05-07T01:19:56.645+0000] {standard_task_runner.py:83} INFO - Job 2636: Subtask scrape_teams_1-8
[2023-05-07T01:19:56.892+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-07T00:00:00+00:00 [running]> on host 6589836e9c08
[2023-05-07T01:19:57.087+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_1-8
AIRFLOW_CTX_EXECUTION_DATE=2023-05-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-07T00:00:00+00:00
[2023-05-07T01:19:57.100+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: scrape_and_save() missing 1 required positional argument: 'current_date'
[2023-05-07T01:19:57.133+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=scrape_and_save_to_csv, task_id=scrape_teams_1-8, execution_date=20230507T000000, start_date=20230507T011956, end_date=20230507T011957
[2023-05-07T01:19:57.150+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2636 for task scrape_teams_1-8 (scrape_and_save() missing 1 required positional argument: 'current_date'; 517)
[2023-05-07T01:19:57.222+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-07T01:19:57.318+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
